### ISSUE TITLE
Update 0.0.8 tag to include prysm binary path changes

### ISSUE THREAD

**Issue by RomiRand** [rocket-pool/smartnode-install#16]
Latest change to prysm binary paths was not included in 0.0.8 tag, so the file won't be found.
Update the 0.0.8 tag to dde897cd57b16c8002af87f832b3ff54b1841c1a.

**Comment by moles1** [comment]
Messing with the tags can cause issues for people installing from the release files while they're being moved. Will leave this issue open and resolve once the next release is out.

**Comment by moles1** [comment]
Fixed
