### ISSUE TITLE
Kill eth1 & eth2 processes spawned in shell scripts gracefully

### ISSUE THREAD

**Issue by moles1** [rocket-pool/smartnode-install#18]
Currently, the processes spawned inside the `eth1`, `eth2` and `validator` containers by shell scripts appear to get left running (and terminated abruptly by Docker after the default timeout).

Add signal traps to the shell scripts to gracefully interrupt these processes when the main process (the shell script) is terminated. Possibly also increase the `stop_grace_period` on the containers to allow time for them to terminate.

**Comment by Dikay900** [comment]
just want to inform that I run into multiple occasions were a simple reboot of the machine or docker image results into geth needing to repair the existing chain. Would be great to shutdown gracefully. I will try to test the related pr if i got time.

**Comment by moles1** [comment]
Fixed in https://github.com/rocket-pool/smartnode-install/commit/be5193156c45f75a11e2054064dda099f7cfb8ef
