### ISSUE TITLE
Smartnode Install for multiple networks

### ISSUE THREAD

**Issue by darcius** [rocket-pool/smartnode-install#2]
Currently the setup script has some hard coded vars which will only work with the testnet. We should make this configurable per network chain ID, so the install script can work on multiple networks if needed.

The file structure could be reorganised to allow this with a clean separation of networks, such as:

`/files/rocketpool.sh`
`/files/setup.sh`

`/files/network/77/pow/config.yml (clientsSupported, providerPow, storageAddress, 
depositContractAddress, withdrawalContractAddress, bootnodes, ethstatsLabel, ethstatsLogin)`

`/files/network/77/beacon/config.yml (clientsSupported, providerBeacon, simulatorETHAddress - address ETH is sent from for the sim)`

Make it so that an extra parameter passed to the install script selected the appropriate network directory to us eg `--network 77` and `setup.sh` can use this.

`clientsSupported` in each client directory could contain a key:value pair list, with the key being the name of the client and value being its docker image ID:Ver eg: `prysm:'prysm:0.1'`

Can add this to the second beta.

**Comment by moles1** [comment]
This is currently implemented in the smartnode install repo. Note that it's probably optimal to separate by eth2 network rather than eth1 network (e.g. we may potentially support several eth2 testnets which all use goerli on the eth1 chain)
