### ISSUE TITLE
Infura log limit workaround

### ISSUE THREAD

**Issue by moles1** [rocket-pool/smartnode-install#20]
Node operators using Infura hit a per-request log limit when their eth2 client is requesting deposit contract logs. Add the following flags to circumvent this:

Lighthouse - `--eth1-blocks-per-log-query`
Prysm - `--eth1-header-req-limit`

**Comment by kidkal** [comment]
![image](https://user-images.githubusercontent.com/901700/108923713-3df6ed80-7631-11eb-82df-4d37bacba04c.png)
See request dashboard in infura.  with limits for both prysm and lighthhouse set at 150 per block, prysm makes about 1000 requests per hour and lighthouse makes about 2000 requests per hour.
