### ISSUE TITLE
Error pulling rocketpool/smartnode-cli

### ISSUE THREAD

**Issue by Alienbyte** [rocket-pool/smartnode-install#7]
Hello there I've finally got the rocketpool service start command working. Yet whenever I execute get the following errors:

https://pastebin.com/Sd56gbVn

Would really appreciate any help.. I've also tried without creating a new image, same issue. I'm also logged in to Docker, but if that's even really part of problem I'm unsure of.

**Comment by moles1** [comment]
It looks like you've installed a (very) old version of the stack somehow, that image no longer exists. If you follow the installation instructions in the readme (https://github.com/rocket-pool/smartnode-install), then it should install using the latest release (https://github.com/rocket-pool/smartnode-install/releases/tag/0.0.3)

**Comment by Alienbyte** [comment]
That's where I'm installing from..

**Comment by moles1** [comment]
The output in the link you posted is from a much older version of Rocket Pool. Did you participate in a previous beta on the same machine you're using now? It seems like the installation has failed and you're running old / leftover code.

I would try doing the following and seeing if you get any different behaviour:
1. Completely remove everything at `~/.rocketpool`
2. Run `which rocketpool` to see if you have an existing binary and delete that
3. Follow the installation instructions from the top

**Comment by Alienbyte** [comment]
Really odd :/ Didn't participate in earlier beta. It's on a brand new instance from digitalocean, and reinstalled multiple times on Ubuntu 16, 18 and 20.

My apologies this is my first experience with docker. I've tried the following steps along with another fresh reinstall, and got past rocketpool service install & rocketpool config, and now I'm getting:

"The INFURA_PROJECT_ID variable is not set. Defaulting to a blank string.
Couldn't connect to Docker daemon at http+docker://localhost - is it running?"

**Comment by moles1** [comment]
No worries at all! :)

Thinking on this more (and considering you're running a brand new instance), I think what might have happened is that I was messing around with the release tags at the exact moment you tried to install the smart node service the first time around - this could have resulted in the installer pulling down the previous release files instead. Just unlucky timing perhaps! Either way, will keep an eye out to see if anyone experiences similar issues.

The error message about the infura project ID is fine, that can be ignored.

The one about connecting to the docker daemon is a permissions issue which happens right after installing docker and gets resolved when you start a new shell session. Good catch, will add a note about that to the docs :)
