### ISSUE TITLE
Add PATH support for Zsh

### ISSUE THREAD

**Issue by actuallymentor** [rocket-pool/smartnode-install#9]
Hello!

Many of us use `zsh` instead of `bash`. In your instructions the `source .profile` triggers a `source` of the `.bashrc` if using the `bash` shell. In order to manually support `zsh` I had to:

1. Run `echo "export PATH=~/bin/:$PATH" >> ~/.zshrc`
2. Run `source ~/.zshrc`

It is unclear to me how you generated the release binary so I'm not able to make a PR. If you have contribution guidelines/docs please let me know.

**Comment by moles1** [comment]
This only concerns documentation, and shouldn't require any changes to the RP binaries. The guides have been updated accordingly:
https://medium.com/rocket-pool/rocket-pool-v2-5-beta-node-operators-guide-77859891766b
https://medium.com/rocket-pool/rocket-pool-smart-nodes-on-aws-c4d45fa5c9ad

**Comment by actuallymentor** [comment]
Thanks for your reaction @moles1!

Since you are adding to the bash path wouldn't it make sense do do a basic `if exists .zshrc then echo ~/.bin to path`?

Again if this is too small for your attention I am happy to make a pull request if you point me to the right place.
